---
- name: copy file
  hosts: dev
  become: true
  vars:
     src: test222.txt
     dest: /tmp/test222.txt 
    
  tasks:
  - name: file copy
    copy:
      src: "{{ src }}"
      dest: "{{ dest }}"
