---
- name: copy file
  hosts: pronixsplunktest01.imanheim.net
  vars:
     src: test222.txt
     dest: /tmp/test222.txt 
    
  tasks:
  - name: file copy
    copy:
      src: "{{ src }}"
      dest: "{{ dest }}"
